# Generated by Django 2.2.1 on 2019-05-26 04:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190525_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Member',
        ),
    ]
