# Generated by Django 2.2.1 on 2019-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190526_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('fo', 'Footbal'), ('ba', 'Basketball'), ('ic', 'Ice Hockey'), ('bs', 'Baseball'), ('ma', 'Martial Arts'), ('go', 'Golf'), ('te', 'Tennis'), ('sw', 'Swimming'), ('tr', 'Track'), ('vo', 'Volleyball'), ('gy', 'Gymnastics'), ('bo', 'Body Building')], max_length=2),
        ),
    ]
