# Generated by Django 2.2.1 on 2019-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20190525_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='is solved'),
        ),
    ]
