# Generated by Django 2.2.1 on 2019-05-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20190525_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pub_date']},
        ),
    ]
